files:
 vox_celeb_splits: Data/timit_split.txt
 vox_celeb_meta: Data/TIMIT/timit_meta.csv
 vox_dev_wav: Data/TIMIT/TRAIN
 vox_test_wav: Data/TIMIT/TEST
 weights_path: Data/model_weights/model.h5
 log_dir: logs

spectrogram:
  sampling_rate: 16000 # Hz
  sample_length: 0.4 # sec
  offset: 0.1 #sec
  fft_window: 1024 # samples
  hop_length: 160 # samples

dataset:
  split: train-dev

generator:
